package frontend;

import backend.Chordy;
import backend.Duration;
import backend.ChordChart;
import jdk.nashorn.internal.objects.Global;
import org.apache.commons.io.FilenameUtils;
import org.jfugue.theory.Key;
import org.jfugue.theory.Note;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

public class ButtonsPanel extends Panel {
    UI userInterface;

    public ArrayList<ImageIcon> getIconList() {
        return iconList;
    }

    private ArrayList<ImageIcon> iconList = new ArrayList<>();
    private JPanel panel;
    private JButton chordButton1;
    private JButton chordButton5;
    private JButton chordButton6;
    private JButton chordButton2;
    private JButton chordButton7;
    private JButton chordButton3;
    private JButton extraButton;
    private JButton chordButton4;

    public ButtonsPanel() {
        panel.setPreferredSize(new Dimension(600, 700));
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("ButtonsPanel");
        frame.setContentPane(new ButtonsPanel().panel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    public void rootButtonHit(JButton rootButton) {
        userInterface.getChordChart().insertUseable(new Chordy(rootButton.getName(), "", Duration.QUARTER));
    }

    public void actionPerformed(ActionEvent evt) {
        //
    }

    public void getButtons() {
        ChordChart chordchard = userInterface.getChordChart();
        GlobalParametersPanel globalParametersPanel = userInterface.getGlobalParametersPanel();
        String gpKey = globalParametersPanel.getKey();
        Key key = new Key(gpKey);
        List<Note> notes = key.getScale().getIntervals().setRoot(key.getRoot().toString()).getNotes();
        for (Note n : notes) {
            try {
                toIcons(n);
            } catch (IOException ioe) {
                ioe.printStackTrace();
            }
        }
    }

    public void toIcons(Note n) throws IOException {
        File folder = new File("graphics/");
        File[] listOfFiles = folder.listFiles();
        String nStr = n.toString();
        for (File f : listOfFiles) {
            if (nStr.substring(0, nStr.length() - 1).equals(FilenameUtils.removeExtension(f.getName()))) {
                BufferedImage image = ImageIO.read(f);
                ImageIcon icon = new ImageIcon(image);
                icon.setDescription(nStr.substring(0, nStr.length() - 1));
                iconList.add(icon);
            }
        }
    }

    public void draw() {
        createUIComponents();
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        //chordButton1 = new JButton(icona);

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 4, new Insets(0, 0, 0, 0), -1, -1));
        chordButton1 = new JButton();
        chordButton1.setText("Button");
        panel.add(chordButton1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        chordButton5 = new JButton();
        chordButton5.setText("Button");
        panel.add(chordButton5, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        chordButton6 = new JButton();
        chordButton6.setText("Button");
        panel.add(chordButton6, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        chordButton2 = new JButton();
        chordButton2.setText("Button");
        panel.add(chordButton2, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        chordButton7 = new JButton();
        chordButton7.setText("Button");
        panel.add(chordButton7, new com.intellij.uiDesigner.core.GridConstraints(1, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        chordButton3 = new JButton();
        chordButton3.setText("Button");
        panel.add(chordButton3, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        extraButton = new JButton();
        extraButton.setText("Button");
        panel.add(extraButton, new com.intellij.uiDesigner.core.GridConstraints(1, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        chordButton4 = new JButton();
        chordButton4.setText("Button");
        panel.add(chordButton4, new com.intellij.uiDesigner.core.GridConstraints(0, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
