package frontend;

import backend.Chordy;
import backend.Duration;
import backend.ChordChart;
import org.jfugue.theory.*;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.util.*;
import java.util.List;

public class ButtonsPanel extends Panel implements ActionListener {
    UI userInterface;

    ArrayList<JButton> usedButtonList = new ArrayList<>();
    ArrayList<JButton> nonUsedButtonList = new ArrayList<>();

    private JPanel panel;
    private JButton chordButton1;
    private JButton chordButton5;
    private JButton chordButton6;
    private JButton chordButton2;
    private JButton chordButton7;
    private JButton chordButton3;
    private JButton extraButton;
    private JButton chordButton4;
    private String extension; //Is this also in global params panel?

    public UI getUserInterface() {
        return userInterface;
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("ButtonsPanel");
        frame.setContentPane(new ButtonsPanel().panel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    public void setUserInterface(UI userInterface) {
        this.userInterface = userInterface;
    }

    public ButtonsPanel() {
        $$$setupUI$$$();
        panel.setPreferredSize(new Dimension(900, 400));
    }

    public void rootButtonHit(JButton rootButton) {
        userInterface.getChordChart().insertUseable(new Chordy(rootButton.getName(), "", Duration.QUARTER));
    }

    public void actionPerformed(ActionEvent evt) {
        JButton button = (JButton) evt.getSource();
        if (!button.equals(extraButton)) {
            ChordChart chordChart = this.getUserInterface().getChordChart();
            String note = ((ImageIcon) button.getIcon()).getDescription();
            Chordy chord = new Chordy(note, this.extension, Duration.QUARTER);
            chordChart.insertUseable(chord);
            this.getUserInterface().setChordChart(chordChart);
        } else {
            //ADD JMENU OR WHATEVER WITH BUTTONS IN NONUSED LIST
        }
    }

    private void getButtons() throws IOException {
//        GlobalParametersPanel globalParametersPanel = userInterface.getGlobalParametersPanel();
 //       setKey(globalParametersPanel.getKey());
        this.setKey(new Key("Cmaj"));
        Set<String> chromaticNotes = ButtonsPanel.getChromaticNotes();
        getKey().getScale().getIntervals().setRoot(getKey().getRoot());
        List<Note> keyNotes = getKey().getScale().getIntervals().getNotes();
        for (Note n : keyNotes) {
            usedButtonList.add(toButton(n));
            String nStr = n.toString();
            chromaticNotes.remove(nStr.substring(0, nStr.length() - 1));
        }
        for (String str : chromaticNotes) {
            nonUsedButtonList.add(toButton(new Note(str)));
        }
    }

    private static Set<String> getChromaticNotes() {
        Intervals chromatic = new Intervals("1 #1 2 #2 3 4 #4 5 #5 6 #6 7 #7");
        chromatic.setRoot("C5");
        Set<String> chromaticNotes = new LinkedHashSet<>();
        for (Note n : chromatic.getNotes()) {
            chromaticNotes.add(Note.getDispositionedToneStringWithoutOctave(1, n.getValue()));
            chromaticNotes.add(Note.getDispositionedToneStringWithoutOctave(-1, n.getValue()));
        }
        return chromaticNotes;
    }

    public void draw() {
        createUIComponents();
    }


    private void createUIComponents() {
        // TODO: place custom component creation code here
        try {
            this.getButtons();
        } catch (IOException ioe) {
            ioe.printStackTrace();
        }
        //I tried to use an array to iterate it doesnt work?
        chordButton1 = usedButtonList.get(0);
        chordButton1.addActionListener(this);
        chordButton2 = usedButtonList.get(1);
        chordButton1.addActionListener(this);
        chordButton3 = usedButtonList.get(2);
        chordButton1.addActionListener(this);
        chordButton4 = usedButtonList.get(3);
        chordButton1.addActionListener(this);
        chordButton5 = usedButtonList.get(4);
        chordButton1.addActionListener(this);
        chordButton6 = usedButtonList.get(5);
        chordButton1.addActionListener(this);
        chordButton7 = usedButtonList.get(6);
        chordButton1.addActionListener(this);
        extraButton = new JButton();
        extraButton.setIcon(new ImageIcon("graphics/EllipseButton.png"));
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel = new JPanel();
        panel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 4, new Insets(0, 0, 0, 0), -1, -1));
        chordButton1.setHideActionText(false);
        panel.add(chordButton1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panel.add(chordButton5, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panel.add(chordButton6, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panel.add(chordButton2, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panel.add(chordButton7, new com.intellij.uiDesigner.core.GridConstraints(1, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panel.add(chordButton3, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        extraButton.setEnabled(true);
        extraButton.setText("");
        panel.add(extraButton, new com.intellij.uiDesigner.core.GridConstraints(1, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panel.add(chordButton4, new com.intellij.uiDesigner.core.GridConstraints(0, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}


