package frontend;

import backend.ChordChart;

import javax.swing.*;
import java.awt.*;

public class GenericUIBuilder implements UIBuilder {
    private UI userInterface;

    //All of these "make" methods need to be tied to the actual GUI
    //but .add is kind of the intuition
    public void makeNotationPanel() {
        userInterface.add(new NotationPanel());
    }

    public void makeButtonsPanel() {
        userInterface.add(new ButtonsPanel(userInterface));
    }

    public void makeButtons() {
        // dothis
    }

    public void makeUI(ChordChart chord) {
        userInterface = new UI(chord);
    }

    public UI getUI() {
        return this.userInterface;
    }

    public void makeGlobalParamsPanel() {
        userInterface.add(new GlobalParametersPanel());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }
}
