package frontend;

import org.jfugue.theory.Key;

import javax.swing.*;
import java.awt.*;

public class GlobalParametersPanel extends Panel {
    private int tempo;
    private JMenu keys;
    private JMenu tempos;
    private JPanel Panel;

    public GlobalParametersPanel() {
    }

    public void draw() {
        new GlobalParametersPanel();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        Panel = new JPanel();
        Panel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return Panel;
    }


    /*
         * Set Key()
         * Called when GUI Action Listener hears a new key getting set
         * from a JMenu
         */

}
