package frontend;

import backend.ChordChart;
import backend.Duration;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class NotationPanel extends Panel {
    //private ArrayList<DrawnChord> drawnChordList;
    private JPanel panel1;
    private JTable TrackerTable;
    private JScrollPane scrollPane;
    private JComboBox<Duration> durBox;
    private JButton delButton;
    private JButton shiftDownButton;
    private JButton shiftUpButton;
    private final String[] COL_NAMES = new String[]{"Root", "Extension", "Duration"};
    private DefaultTableModel tableModel;
    private final DefaultComboBoxModel<Duration> DB_MODEL = new DefaultComboBoxModel<Duration>(new Duration[]{
            Duration.WHOLE,
            Duration.HALF,
            Duration.QUARTER,
            Duration.EIGHTH,
            Duration.SIXTEENTH,
            Duration.THIRTYSECOND,
            Duration.SIXTYFOURTH,
            Duration.ONETWENTYEIGHTH
    });


    public NotationPanel(UI userInterface) {
        super(userInterface);
        $$$setupUI$$$();
        panel1.setPreferredSize(new Dimension(500, 500));
        updateTable();
        setUpControl();
    }


    //JTable TrackerTable = new JTable(ChordChart.chordList);
    public void draw(Object arg) {
        updateTable();
    }

    /*
        // if this sucks just delete it:
        public void updateDrawnChordList(){
            ArrayList<DrawnChord> retlist = new ArrayList<>();
            for (Useable chord : userInterface.chordChart.getChordList()){
                retlist.add(new DrawnChord((Chordy) chord));
            }
            this.drawnChordList = retlist;
        }
    */
    private void updateTableModel() {
        this.tableModel = new DefaultTableModel(
                this.getUserInterface().getChordChart().toTableArray(),
                COL_NAMES
        );
    }

    private void updateTable() {
        updateTableModel();
        this.TrackerTable.setModel(this.tableModel);
    }

    private void setUpControl() {
        // set up duration box:
        durBox.setModel(DB_MODEL);
        durBox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                tableSetDur(TrackerTable.getSelectedRows(), (Duration) durBox.getSelectedItem());
            }
        });

        // set up delete button:
        delButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                tableDelChord(TrackerTable.getSelectedRows());
            }
        });

        // set up shiftUp button:
        shiftUpButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                int placeholder = TrackerTable.getSelectedRow();
                tableShiftUp(TrackerTable.getSelectedRow());
                TrackerTable.changeSelection(placeholder - 1, 0, false, false);
            }
        });

        // set up shiftDown button:
        shiftDownButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                int placeholder = TrackerTable.getSelectedRow();
                tableShiftDown(TrackerTable.getSelectedRow());
                TrackerTable.changeSelection(placeholder + 1, 0, false, false);
            }
        });
    }

    private void tableShiftDown(int i) {
        ChordChart cc = getUserInterface().getChordChart();
        cc.moveChord(i, i + 1);
        getUserInterface().setChordChart(cc);
    }

    private void tableShiftUp(int i) {
        ChordChart cc = getUserInterface().getChordChart();
        cc.moveChord(i, i - 1);
        getUserInterface().setChordChart(cc);
    }

    private void tableDelChord(int[] array) {
        ChordChart cc = getUserInterface().getChordChart();
        for (int i = 0; i < array.length; i++) {
            cc.delChord(array[i] - i);
        }
        getUserInterface().setChordChart(cc);
    }

    private void tableSetDur(int[] array, Duration duration) {
        ChordChart cc = getUserInterface().getChordChart();
        getUserInterface().setDuration(duration);
        for (int i = 0; i < array.length; i++) {
            cc.getUseable(array[i]).setDur(duration);
        }
        getUserInterface().setChordChart(cc);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
        scrollPane = new JScrollPane();
        panel1.add(scrollPane, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 3, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        TrackerTable = new JTable();
        scrollPane.setViewportView(TrackerTable);
        durBox = new JComboBox();
        panel1.add(durBox, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        delButton = new JButton();
        delButton.setText("Delete Selected");
        delButton.setToolTipText("delete the chord selected in the Tracker Table");
        panel1.add(delButton, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel2, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        shiftDownButton = new JButton();
        shiftDownButton.setText("Shift Down");
        panel2.add(shiftDownButton, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        shiftUpButton = new JButton();
        shiftUpButton.setText("Shift Up");
        panel2.add(shiftUpButton, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
